services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: django
    ports:
      - "8000:8000"
    command: >
      bash -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate &&
      pytest --import-mode=importlib shop/tests/tests_views/test_category_and_subcategory
      "
    volumes:
      - .:/kikimoraback
    environment:
      - DJANGO_SETTINGS_MODULE=kikimoraback.settings_test
      - DEBUG=0
    depends_on:
      testdb:
        condition: service_healthy

  testdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: testdb

    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s