version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    restart: always
    expose:
      - "8001:8000" # Меняем внешний порт на 8001, чтобы не конфликтовать с nginx
    volumes:
      - static_volume:/kikimoraback/static
      - media_volume:/kikimoraback/media
    environment:
      - DJANGO_SECRET_KEY=секретный_ключ
      - DJANGO_DEBUG=False
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build:
      context: .
    command: celery -A kikimoraback worker --loglevel=info
    depends_on:
      - django
      - redis

  celery-beat:
    build:
      context: .
    command: celery -A kikimoraback beat --loglevel=info
    depends_on:
      - django
      - redis

  redis:
    image: redis:latest
    restart: always
    expose:
      - "6379"

volumes:
  static_volume:
  media_volume:
