version: "3.9"
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    ports:
    - "8000:8000"
    command: bash -c "python manage.py makemigrations && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/kikimoraback
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build:
      context: .
    command: celery -A kikimoraback worker -l INFO
    volumes:
      - .:/kikimoraback
    depends_on:
      - django
      - redis

  redis:
    image: redis:latest