services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django
    restart: always
    expose:
      - "8000"
    volumes:
      - /var/www/kikimora/static:/kikimoraback/static  # Монтируем статические файлы на хост
      - /var/www/kikimora/media:/kikimoraback/media     # Монтируем медиа-файлы на хост
      - /logs:/logs
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CELERY_BROKER=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
      - DJANGO_SETTINGS_MODULE=kikimoraback.settings_prod
    depends_on:
      redis:
        condition: service_healthy

    user: "${UID}:${GID}"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.prod

    command: celery -A kikimoraback worker -l INFO -E  -c 4
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CELERY_BROKER=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
      - DJANGO_SETTINGS_MODULE=kikimoraback.settings_prod
    depends_on:
      redis:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "celery", "-A", "kikimoraback", "inspect", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A kikimoraback beat --loglevel=info
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CELERY_BROKER=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
      - DJANGO_SETTINGS_MODULE=kikimoraback.settings_prod
    depends_on:
      redis:
        condition: service_healthy


  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --save 900 1 --save 300 10
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 3s

  flower:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/0
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      bash -c "
      celery -A kikimoraback flower --port=5555 --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}"
    depends_on:
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      django:
        condition: service_started
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "7000:3000"  # Порт для интерфейса Grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_started

volumes:
  grafana-storage:
    driver: local
    driver_opts:
      type: none
      device: /grafana
      o: bind