services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django
    ports:
      - "8000:8000"
    command: >
      bash -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate &&
      python manage.py boot_cache &&
      uvicorn kikimoraback.asgi:application --host 0.0.0.0 --port 8000 --reload --reload-dir /kikimoraback
      "
    volumes:
      - .:/kikimoraback
    environment:
      - DJANGO_SETTINGS_MODULE=kikimoraback.settings_dev
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - UVICORN_RELOAD_USE_POLLING=true
    depends_on:
      redis:
        condition: service_healthy

  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A kikimoraback worker -l INFO -E  -c 4
    environment:
      - DJANGO_SETTINGS_MODULE=kikimoraback.settings_dev
    volumes:
      - .:/kikimoraback
    depends_on:
      redis:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "celery", "-A", "kikimoraback", "inspect", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 5

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A kikimoraback beat -l INFO
    volumes:
      - .:/kikimoraback
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s

  flower:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: flower
    ports:
      - "5555:5555"
    command: >
      bash -c "
      celery -A kikimoraback flower --port=5555 --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}"
    depends_on:
      celery:
        condition: service_healthy
      redis:
        condition: service_healthy
