services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations shop && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/kikimoraback
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build:
      context: .
    command: celery -A kikimoraback worker -l INFO
    volumes:
      - .:/kikimoraback
    depends_on:
      - django
      - redis

  celery-beat:
    build:
      context: .
    command: celery -A kikimoraback beat -l INFO
    volumes:
      - .:/kikimoraback
    depends_on:
      - django
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
