services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    restart: always
    expose:
      - "8000"
    volumes:
      - /var/www/kikimora/static:/kikimoraback/static  # Монтируем статические файлы на хост
      - /var/www/kikimora/media:/kikimoraback/media     # Монтируем медиа-файлы на хост
      - /logs:/logs
    environment:
      - DJANGO_SECRET_KEY=секретный_ключ
      - DJANGO_DEBUG=False
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - redis
    user: "${UID}:${GID}"
    
  celery:
    build:
      context: .
    command: celery -A kikimoraback worker --loglevel=info
    depends_on:
      - django
      - redis
  celery-beat:
    build:
      context: .
    command: celery -A kikimoraback beat --loglevel=info
    depends_on:
      - django
      - redis
  redis:
    image: redis:latest
    restart: always
    expose:
      - "6379"
