# Generated by Django 5.1 on 2025-02-21 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_discount_end_alter_discount_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 11, 46, 54, 608053, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 11, 46, 54, 608026, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='permalink',
            field=models.CharField(db_index=True, default=None, max_length=200, null=True),
        ),
    ]
