# Generated by Django 5.1 on 2025-02-28 09:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0039_alter_discount_end_alter_discount_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 28, 9, 48, 25, 269436, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 28, 9, 48, 25, 269421, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=10)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
        ),
    ]
