# Generated by Django 5.1 on 2025-02-28 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0041_remove_producttag_product_id_product_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 28, 13, 15, 1, 371087, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 28, 13, 15, 1, 371071, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
