# Generated by Django 5.1 on 2025-03-05 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_alter_discount_end_alter_discount_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 10, 21, 39, 368455, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 10, 21, 39, 368439, tzinfo=datetime.timezone.utc)),
        ),
    ]
