# Generated by Django 5.1 on 2025-03-10 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0057_alter_discount_end_alter_discount_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="end",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 10, 14, 5, 1, 629330, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 10, 14, 5, 1, 629311, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
