# Generated by Django 5.1 on 2025-03-12 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0085_alter_discount_end_alter_discount_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 11, 57, 53, 937876, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 11, 57, 53, 937851, tzinfo=datetime.timezone.utc)),
        ),
    ]
