# Generated by Django 5.1.8 on 2025-04-16 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0146_alter_discount_end_alter_discount_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="end",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
