# Generated by Django 5.1.8 on 2025-05-29 09:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0147_alter_discount_end_alter_discount_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_decimal",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_decimal",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
    ]
