# Generated by Django 5.1.8 on 2025-05-29 09:39

from django.db import migrations
from decimal import Decimal


def forwards(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for product in Product.objects.all():
        # Переводим float в decimal через str → избегаем проблем с точностью
        product.price_decimal = Decimal(str(product.price))
        product.weight_decimal = Decimal(str(product.weight))
        product.save(update_fields=['price_decimal', 'weight_decimal'])


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0148_product_price_decimal_product_weight_decimal"),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
