# Generated by Django 5.1.8 on 2025-05-29 09:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0149_migrate_float_to_decimal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_decimal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Цена товара",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight_decimal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Вес товара в киллограммах",
                max_digits=10,
            ),
        ),
    ]
