# Generated by Django 5.1.8 on 2025-05-29 15:02

from django.db import migrations
from decimal import Decimal

def forwards(apps, schema_editor):
    Discount = apps.get_model('shop', 'Discount')
    for discount in Discount.objects.all():
        discount.value_decimal = Decimal(str(discount.value))
        discount.save(update_fields=["value_decimal"])


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0153_discount_value_decimal"),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
