# Generated by Django 5.1.8 on 2025-05-30 12:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0155_remove_discount_value_decimal_alter_discount_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="promosystem",
            name="amount_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Процент скидки или сумма скидки",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
