# Generated by Django 5.1.8 on 2025-05-30 12:39

from django.db import migrations
from decimal import Decimal


def forwards(apps, schema_editor):
    PromoSystem = apps.get_model("shop", "PromoSystem")
    for promo in PromoSystem.objects.all():
        promo.amount_decimal = Decimal(str(promo.amount))
        promo.save(update_fields=["amount_decimal"])


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0156_promosystem_amount_decimal"),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
