# Generated by Django 5.1.8 on 2025-05-30 12:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0157_migrate_float_to_decimal_promo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promosystem",
            name="amount_decimal",
        ),
        migrations.AlterField(
            model_name="promosystem",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Процент скидки или сумма скидки",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
